unit LayList;

interface

type
  TListElement = record
    id  :integer;
    name:PUnicodeChar;
  end;

{Group tags from FEATURETAGS.HIE}
const
  FeatureTags: array of TListElement = nil;
const
  DefFeatureTags: array [0..139] of TListElement = (
    (id:  1; name:'DUNGEON CRYPT'),
    (id:  2; name:'DUNGEONS RANDOM'),
    (id:  3; name:'DUNGEON CAVE'),
    (id:  4; name:'CHESTS'),
    (id:  5; name:'CHESTS RARE'),
    (id:  6; name:'CHESTS STANDARD'),
    (id:  7; name:'SHRINE LOOTABLE'),
    (id:  8; name:'WAYPOINT PADS'),
    (id: 13; name:'QUEST SET PIECES'),
    (id: 15; name:'STONE HEAD 1'),
    (id: 17; name:'Water Shrine 1'),
    (id: 18; name:'Water Shrine 2'),
    (id: 19; name:'Water Shrine 3'),
    (id: 20; name:'Water Shrine 4'),
    (id: 21; name:'Water Shrine 5'),
    (id: 22; name:'CHEST LOCKED'),
    (id: 23; name:'CHESTS_SPECIAL'),
    (id: 24; name:'WILDERNESS ACT1'),
    (id: 25; name:'WILDERNESS ACT1 ZONE1'),
    (id: 26; name:'ROAD ACT1'),
    (id: 27; name:'ROAD ACT1 ZONE1'),
    (id: 28; name:'WeaponRacks'),
    (id: 30; name:'CHEST GHOST'),
    (id: 31; name:'DUNGEON Z1CEMETARY'),
    (id: 32; name:'DUNGEON CATACOMBS'),
    (id: 34; name:'Merryweather bush'),
    (id: 35; name:'Vanquisher Scout'),
    (id: 36; name:'A1-Pass2-cultists'),
    (id: 38; name:'A1-RandomEvents'),
    (id: 39; name:'A1-RandomEvents-Bandits'),
    (id: 40; name:'DeadAdventurers'),
    (id: 41; name:'ScrollSpawner'),
    (id: 43; name:'A2-RandomEvents'),
    (id: 45; name:'A2-BigMonsterSpawners'),
    (id: 46; name:'Vault_Sarcophagus'),
    (id: 47; name:'A2-TowerOfTheMoon'),
    (id: 48; name:'A1-RandomQuests-GhostBoat'),
    (id: 50; name:'A1-RandomEvents-Goblins'),
    (id: 51; name:'A2-MerchantShip'),
    (id: 53; name:'DUNGEON A2TutaranMain'),
    (id: 54; name:'A1-RandomEvents-Bears'),
    (id: 55; name:'FishingHole'),
    (id: 56; name:'A3-RandomEvents'),
    (id: 57; name:'A2-RandomEvents-Ezro'),
    (id: 58; name:'A2-RANDOMEVENTS-Jackals'),
    (id: 59; name:'A2-SandChestEvent'),
    (id: 60; name:'A2-SandGolem'),
    (id: 61; name:'A2-BoneGolem'),
    (id: 62; name:'DUNGEON MUCKERY'),
    (id: 63; name:'DUNGEON DANK HALLOW'),
    (id: 64; name:'DUNGEON VAULT'),
    (id: 65; name:'DUNGON DRAGON'),
    (id: 66; name:'A1-Shrine'),
    (id: 67; name:'A2-Shrine'),
    (id: 68; name:'A3-Shrine'),
    (id: 69; name:'Catacomb-RandomEvents'),
    (id: 70; name:'A2-RandomEvents-Lizardmen'),
    (id: 71; name:'Vault-RandomEvents'),
    (id: 72; name:'VaultEvent-Speech'),
    (id: 73; name:'A4-RandomEvents'),
    (id: 74; name:'A3-RandomEvents-Varks'),
    (id: 75; name:'A2-RandomQuests-PiratesCove'),
    (id: 76; name:'A2-KingCrabQuest'),
    (id: 77; name:'A1-Quest_Cliff_Ruins'),
    (id: 78; name:'A1-Quest_ChestOfPools'),
    (id: 79; name:'A1-Quest_ChestOfRivers'),
    (id: 80; name:'A1-Quest_ChesetOfTides'),
    (id: 81; name:'ChestMimics'),
    (id: 82; name:'A2-Surveyor'),
    (id: 83; name:'A2-ManaVentDungeonEntrance'),
    (id: 84; name:'A1-deathTower'),
    (id: 85; name:'A3-MoonShrine'),
    (id: 86; name:'a2-evilDen'),
    (id: 88; name:'A2-Stone_Coffins'),
    (id: 89; name:'A2-Stone_Coffin 1'),
    (id: 90; name:'A2-Stone_Coffin 2'),
    (id: 91; name:'A2-Stone_Coffin 3'),
    (id: 92; name:'A3_Werewolf_Cellar'),
    (id: 93; name:'A3_Werewolf_Cellar_Basement'),
    (id: 94; name:'A3_Werewolf_Cellar_Spawner'),
    (id: 95; name:'A3-Swamp-CatacombsEntrance'),
    (id: 96; name:'A3_Trolls'),
    (id: 97; name:'A3-Witch-Items-Spawner'),
    (id: 98; name:'A3-Witch-Items-Wraiths'),
    (id: 99; name:'A3-Witch-Items-ZombieGrave'),
    (id:100; name:'A3-Witch-Items-ArenaPortal'),
    (id:101; name:'DUNGEON BROODHIVE'),
    (id:102; name:'A3_Witch_Bell'),
    (id:103; name:'A3_BlightSlugSpawner'),
    (id:104; name:'A3_RotCryptGemSpawn'),
    (id:107; name:'A2-RandomEvents-DesertRatlins'),
    (id:109; name:'DUNGEON QUARRY'),
    (id:110; name:'A3-RandomEvents-Trolls'),
    (id:111; name:'A3-RandomEvents-ChestEvents'),
    (id:113; name:'PhaseBeast-Choice_Bad'),
    (id:114; name:'PhaseBeast-Choice_Ok'),
    (id:115; name:'PhaseBeast-Choice_Good'),
    (id:116; name:'PhaseBeast-Choice'),
    (id:117; name:'A3-DeathCircle'),
    (id:118; name:'A3-GlyphsOfElements'),
    (id:119; name:'A3-GlyphOfWater'),
    (id:120; name:'A3-GlyphOfWood'),
    (id:121; name:'A3-GlyphOfFire'),
    (id:122; name:'A3-GlyphOfAir'),
    (id:125; name:'A3-Pedestals'),
    (id:126; name:'A3-PedestalOfWater'),
    (id:127; name:'A3-PedestalOfWood'),
    (id:128; name:'A3-PedestalOfFire'),
    (id:129; name:'A3-PedestalOfAir'),
    (id:130; name:'A3-Battlefield_Pikes'),
    (id:131; name:'A3-Battlefield_Pike_1'),
    (id:132; name:'A3-Battlefield_Pike_2'),
    (id:133; name:'A3-Battlefield_Pike_3'),
    (id:134; name:'A3-Battlefield_Pike_4'),
    (id:135; name:'A3-Spirit Dragon'),
    (id:136; name:'Dungeon Quarry Entrance'),
    (id:137; name:'PhaseBeast-PirateTreasure'),
    (id:138; name:'PhaseBeast-PirateTreasure_Good'),
    (id:139; name:'PhaseBeast-PirateTreasure_Ok'),
    (id:140; name:'A2-NGPlusRisingStatue'),
    (id:141; name:'DUNGEON NG_BEARCAVE'),
    (id:143; name:'DUNGEON NG_WELLSPRINGTREASURY'),
    (id:144; name:'DUNGEON NG_ICELABS'),
    (id:145; name:'Nether Events'),
    (id:146; name:'Nether Altar'),
    (id:147; name:'ENTRANCEEXITNODE'),
    (id:148; name:'ENTRANCENODE'),
    (id:149; name:'EXITNODE'),
    (id:150; name:'A2-NetherPortal'),
    (id:151; name:'A3-NetherPortal'),
    (id:152; name:'A1-NetherPortal'),
    // Unearthed Arcana mod
    (id:153; name:'TL1-SHRINE'),
    (id:154; name:'A1-SHRINEGAMBLER'),
    (id:155; name:'A2-SHRINEGAMBLER'),
    (id:156; name:'A3-SHRINEGAMBLER'),
    (id:157; name:'A1-CARAVANATTACK'),
    (id:158; name:'A1-LOSTITEM'),
    (id:159; name:'A3_HOWLINGCAVE_N'),
    (id:160; name:'A3_HOWLINGCAVE_S'),
    (id:161; name:'A2-COLLAPSINGCAVE')
  );

{Layout Object [menu] icons}
const
  ObjIconImgList = 'objicons.il';
const
  ObjIcons: array [0..141] of TListElement = (
    (id: -1; name:'action'),
    (id: 63; name:'ai_choice'),
    (id: 63; name:'ai_control_timeline'),
    (id: 63; name:'ai_controller'),
    (id: 63; name:'ai_goto'),
    (id: 63; name:'ai_joystick'),
    (id: 63; name:'ai_levitation'),
    (id: 63; name:'ai_monster_spline'),
    (id: 63; name:'ai_object_control'),
    (id: 63; name:'ai_object_spline'),
    (id: 63; name:'ai_perform_animation'),
    (id: 63; name:'ai_perform_attack'),
    (id: 63; name:'ai_pickup'),
    (id: 63; name:'ai_push_pull'),
    (id: 63; name:'ai_tank_control'),
    (id: 63; name:'aiinfo'),
    (id: 63; name:'aitolayout'),
    (id: -1; name:'animationnode'),
    (id: -1; name:'armor'),
    (id: -1; name:'bone'),
    (id: -1; name:'boxgroup'),
    (id:  0; name:'boxtrigger'),
    (id:  1; name:'button'),
    (id:  2; name:'camera'),
    (id: -1; name:'camera_lock'),
    (id:  3; name:'checkbox'),
    (id:  4; name:'chest'),
    (id: -1; name:'cinematic'),
    (id:  5; name:'clapperboard'),
    (id:  6; name:'clock'),
    (id: -1; name:'collision'),
    (id: -1; name:'construct'),
    (id:  7; name:'container'),
    (id:  8; name:'counter'),
    (id: -1; name:'coupdegrace'),
    (id: -1; name:'damage'),
    (id:  9; name:'damageshape'),
    (id: -1; name:'decalfolder'),
    (id: 10; name:'die'),
    (id: 11; name:'drag'),
    (id: 12; name:'draganddrop'),
    (id: 13; name:'dropdown'),
    (id: -1; name:'dungeon'),
    (id: -1; name:'editor_only_group'),
    (id: -1; name:'effectpercent'),
    (id: -1; name:'electricity'),
    (id: 14; name:'emitter'),
    (id: -1; name:'environmentsound'),
    (id: 15; name:'exclamation'),
    (id: -1; name:'exit'),
    (id: -1; name:'eye'),
    (id: 16; name:'flag'),
    (id: 17; name:'folder'),
    (id: -1; name:'folder_blue'),
    (id: -1; name:'folder_green'),
    (id: -1; name:'folder_red'),
    (id: -1; name:'folder_yellow'),
    (id: 18; name:'frame'),
    (id: 19; name:'frameblocker'),
    (id: 20; name:'gate'),
    (id: 21; name:'gear'),
    (id: 22; name:'image'),
    (id: -1; name:'interactable_layout'),
    (id: -1; name:'interactable_point'),
    (id: -1; name:'interactable_range'),
    (id: -1; name:'iron_group'),
    (id: -1; name:'jump_end'),
    (id: -1; name:'jump_start'),
    (id: 23; name:'keyboard'),
    (id: -1; name:'kill'),
    (id: 24; name:'layoutlink'),
    (id: 25; name:'layoutlink_controller'),
    (id: 26; name:'layoutlinkparticle'),
    (id: 27; name:'light'),
    (id: 28; name:'light_scheme'),
    (id: -1; name:'list'),
    (id: -1; name:'loadscreen'),
    (id: 29; name:'logicgroup'),
    (id: 30; name:'missile'),
    (id: 31; name:'model'),
    (id: 32; name:'money'),
    (id: 33; name:'monster'),
    (id: -1; name:'monster_group'),
    (id: -1; name:'motion'),
    (id: 34; name:'mousepassthrough'),
    (id: -1; name:'movingplatform'),
    (id: 35; name:'outputcounter'),
    (id: -1; name:'parent'),
    (id: 36; name:'particle'),
    (id: -1; name:'passthrough'),
    (id: 37; name:'pathing'),
    (id: -1; name:'pet'),
    (id: 38; name:'piece'),
    (id: -1; name:'player'),
    (id: 39; name:'playersphere'),
    (id: -1; name:'positionlock'),
    (id: 40; name:'progressbar'),
    (id: -1; name:'pulse'),
    (id: -1; name:'punchhelper'),
    (id: -1; name:'quality'),
    (id: -1; name:'quest'),
    (id: 41; name:'question'),
    (id: -1; name:'react_group'),
    (id: 42; name:'remove'),
    (id: -1; name:'respawner'),
    (id: 43; name:'save'),
    (id: -1; name:'save_desk'),
    (id: 44; name:'shake'),
    (id: 63; name:'shakeai'),
    (id: 45; name:'skill'),
    (id: 46; name:'skipcutscene'),
    (id: 47; name:'sound'),
    (id: 48; name:'spawn'),
    (id: -1; name:'spawncontroller'),
    (id: -1; name:'spawnpoint'),
    (id: -1; name:'sprite'),
    (id: -1; name:'stats'),
    (id: 49; name:'stop'),
    (id: -1; name:'swordforge'),
    (id: 50; name:'teleport'),
    (id: -1; name:'terrain'),
    (id: 51; name:'text'),
    (id: 52; name:'textinput'),
    (id: -1; name:'time_glow'),
    (id: 53; name:'timeline'),
    (id: -1; name:'timeline_proximity'),
    (id: -1; name:'timer'),
    (id: -1; name:'tone_in'),
    (id: 54; name:'tool'),
    (id: -1; name:'tutorial'),
    (id: 55; name:'uibutton'),
    (id: 56; name:'uiimage'),
    (id: 57; name:'uitext'),
    (id: 58; name:'uiwindow'),
    (id: 59; name:'unlock'),
    (id: -1; name:'variable_operator'),
    (id: -1; name:'visworldbox'),
    (id: 60; name:'wardrobe'),
    (id: 61; name:'warper'),
    (id: 62; name:'waypointactivator'),
    (id: -1; name:'window'),
    (id: -1; name:'worldshift')
  );


implementation

end.
