{different lists for layout editor and other}

[Interpolation:TL2]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Quaternion'
6='No interpolation'
7='Use Timeline Default'

[Interpolation:Hob]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Quaternion'
6='No interpolation'
7='Hex Color'
8='Animation'
9='Animation Calculated'
10='Use Timeline Default'

[Interpolation:RG]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Quaternion'
6='No interpolation'
7='Use Timeline Default'

[Interpolation:RGO]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Catmull-Rom'
6='Quaternion'
7='No interpolation'
8='Use Timeline Default'

[Direction]

[Position]

[Shape]
POINT
ANGLE
SPHERE

[Game Mode]
1='NORMAL',
2='NEW GAME PLUS'

[Choice]
0='ALL',
1='Weight',
2='Random Chance'

[Operator]
0='EQUAL',
1='LESS THAN',
2='LESS THAN OR EQUAL',
3='GREATER THAN',
4='GREATER THAN OR EQUAL',
5='NOT EQUAL'
6='DO NOT COMPARE'
