{different lists for layout editor and other}
{Elements, Difficulty}

[Interpolation:TL2]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Quaternion'
6='No interpolation'
7='Use Timeline Default'

[Interpolation:Hob]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Quaternion'
6='No interpolation'
7='Hex Color'
8='Animation'
9='Animation Calculated'
10='Use Timeline Default'

[Interpolation:RG]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Quaternion'
6='No interpolation'
7='Use Timeline Default'

[Interpolation:RGO]
0='Linear'
1='Linear Round'
2='Linear Round Down'
3='Linear Round Up'
4='Spline'
5='Catmull-Rom'
6='Quaternion'
7='No interpolation'
8='Use Timeline Default'

[Direction]

[Position]

[Shape]
Angle
Box
Line
Point
Sphere

POINT
ANGLE
SPHERE

[Game Mode]
1='NORMAL',
2='NEW GAME PLUS'

[Choice]
0='ALL',
1='Weight',
2='Random Chance'

[Operator]
0='EQUAL',
1='LESS THAN',
2='LESS THAN OR EQUAL',
3='GREATER THAN',
4='GREATER THAN OR EQUAL',
5='NOT EQUAL'
6='DO NOT COMPARE'

[Steam tags]
1=Armor
2=Art
3=Audio
4=Balance
5=Bosses
6=Characters
7=Classes
8=Co-op
9=Game Modes
10=Gameplay
11=Items
12=Levels
13=Maps
14=Merchants
15=Models
16=Monsters
17=Multiplayer
18=Music
19=Pets
20=Pvp
21=Quests
22=Recipes
23=Skills
24=Socketables
25=Story
26=Textures
27=UI
28=Weapons
